#!/bin/sh

export CONFIG_DIR="$HOME/config"
export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"

# background
[[ -e ~/.fehbg ]] && source ~/.fehbg

# hide mouse coursor when it isn't used
unclutter -root -visible &

# pulse audio session
start-pulseaudio-x11

# dynamic colour temperature adjustment
redshift -c ${CONFIG_DIR}/redshift.conf &

# disks automounting
# udiskie &

# gpg agent
# gpg-connect-agent updatestartuptty /bye

# Network Manager applet
nm-applet &
